PREFIX ex: <http://example.org/traffic/>
SELECT ?latitude ?longitude ?accidentCategoryCode
WHERE { ?a a ex:TrafficAccident ; ex:latitude ?latitude ; ex:longitude ?longitude ; ex:accidentCategoryCode ?accidentCategoryCode . }
